services:
  - type: web
    name: shark-bleu-iptv
    env: python
    region: frankfurt
    buildCommand: "python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "shark-bleu-iptv.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.11"